# 1.4.4 Smoothing Images

## Kernel Convolution

In [1]:
import cv2
import numpy as np
from matplotlib import pyplot as plt

In [2]:
l=1
kernel = np.array([[0,-1,0],[-1,4,-1],[0,-1,0]],np.float32)

In [3]:
kernel

array([[ 0., -1.,  0.],
       [-1.,  4., -1.],
       [ 0., -1.,  0.]], dtype=float32)

In [4]:
img = np.random.randint(10, size=(12,12))
#img = np.ones((10,10),np.float32)

In [5]:
img

array([[2, 1, 8, 7, 2, 8, 4, 4, 8, 6, 6, 0],
       [7, 7, 9, 5, 6, 7, 6, 3, 1, 9, 0, 9],
       [7, 7, 8, 0, 1, 1, 8, 1, 5, 9, 1, 9],
       [6, 9, 7, 1, 0, 0, 6, 2, 8, 9, 7, 3],
       [7, 7, 4, 0, 1, 4, 8, 1, 5, 7, 3, 6],
       [2, 6, 9, 1, 0, 5, 8, 4, 0, 3, 5, 1],
       [1, 8, 6, 7, 7, 7, 9, 5, 6, 0, 1, 9],
       [0, 6, 4, 6, 8, 9, 2, 9, 3, 2, 5, 2],
       [2, 7, 7, 0, 6, 4, 2, 0, 7, 7, 6, 2],
       [3, 0, 4, 3, 5, 2, 1, 4, 4, 1, 7, 2],
       [0, 3, 8, 9, 7, 4, 1, 0, 1, 1, 2, 7],
       [3, 9, 3, 7, 1, 4, 8, 5, 7, 5, 4, 2]])

In [6]:
h,w=img.shape

In [7]:
print(h,w)

12 12


In [8]:
dst = np.zeros((h,w))

In [9]:
for i in range(l,h-l):
    for j in range(l,w-l):
        t=0
        for p in range(-l,l+1):
            for q in range(-l,l+1):
                t += kernel[p+l,q+l]*img[i+p,j+q]
        dst[i,j]=t        

In [10]:
img

array([[2, 1, 8, 7, 2, 8, 4, 4, 8, 6, 6, 0],
       [7, 7, 9, 5, 6, 7, 6, 3, 1, 9, 0, 9],
       [7, 7, 8, 0, 1, 1, 8, 1, 5, 9, 1, 9],
       [6, 9, 7, 1, 0, 0, 6, 2, 8, 9, 7, 3],
       [7, 7, 4, 0, 1, 4, 8, 1, 5, 7, 3, 6],
       [2, 6, 9, 1, 0, 5, 8, 4, 0, 3, 5, 1],
       [1, 8, 6, 7, 7, 7, 9, 5, 6, 0, 1, 9],
       [0, 6, 4, 6, 8, 9, 2, 9, 3, 2, 5, 2],
       [2, 7, 7, 0, 6, 4, 2, 0, 7, 7, 6, 2],
       [3, 0, 4, 3, 5, 2, 1, 4, 4, 1, 7, 2],
       [0, 3, 8, 9, 7, 4, 1, 0, 1, 1, 2, 7],
       [3, 9, 3, 7, 1, 4, 8, 5, 7, 5, 4, 2]])

In [11]:
dst

array([[  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.],
       [  0.,   4.,   8.,  -2.,   9.,   7.,   2.,   0., -21.,  20., -25.,
          0.],
       [  0.,  -3.,   9., -15.,  -3., -12.,  18., -14.,   1.,  12., -21.,
          0.],
       [  0.,   9.,   6.,  -3.,  -3., -11.,   6.,  -8.,  11.,   5.,  12.,
          0.],
       [  0.,   2.,  -7.,  -7.,   0.,   2.,  13., -15.,   4.,   8., -13.,
          0.],
       [  0.,  -2.,  19., -12., -14.,   1.,   6.,   2., -18.,   0.,  12.,
          0.],
       [  0.,  13.,  -4.,   8.,   6.,  -2.,  14.,  -8.,  16., -12., -15.,
          0.],
       [  0.,   5.,  -9.,   5.,   4.,  15., -21.,  26., -12.,  -7.,   9.,
          0.],
       [  0.,  13.,  13., -22.,   7.,  -3.,   1., -22.,  14.,  12.,   3.,
          0.],
       [  0., -17.,  -2.,  -6.,   2.,  -6.,  -5.,  11.,   3., -15.,  17.,
          0.],
       [  0.,  -5.,  13.,  11.,   9.,   2.,  -9., -11.,  -8.,  -5., -11.,
          0.],
       [  0.,   0.,  

In [14]:
img = cv2.imread('./Image/lena.png', 0)

In [15]:
h,w=img.shape

In [16]:
dst = np.zeros((h-2*l,w-2*l),np.uint8)

In [17]:
for i in range(l,h-l):
    for j in range(l,w-l):
        t=0
        for p in range(-l,l+1):
            for q in range(-l,l+1):
                t += kernel[p+l,q+l]*img[i+p,j+q]
        dst[i-l,j-l]=t 

In [18]:
cv2.imshow('img',img)
cv2.imshow('dst',dst)
cv2.waitKey(0)
cv2.destroyAllWindows()